---
- name: "Ensure password reuse is limited "
  lineinfile:
      path: /etc/pam.d/common-password
      regexp: '^password(.*)[success=1 default=ignore](.*)pam_unix.so(.*)obscure(.*)sha512'
      line: "password	[success=1 default=ignore]	pam_unix.so obscure remember={{ HISTORY }} sha512"
      state: present

