---
- hosts: all
  become: true
  ignore_errors: true
  vars:
    - pkg_name: acl
    - pkg_version: "2.2"
  tasks:
   
    - name: Gather the  package facts
      package_facts:
        manager: auto

    - name: "check whether {{ pkg_name }} is installed"
      debug:
        var:  ansible_facts.packages[pkg_name]
      when: (pkg_name in ansible_facts.packages) and (ansible_facts.packages[pkg_name][0].version >= pkg_version)

    - debug:
        msg: "{{ pkg_name }} is not installed"
      when: pkg_name not in ansible_facts.packages